### ISSUE TITLE
Automation: mqtt_person1_away.yaml

### ISSUE THREAD

**Issue by r3m0dul8** [DubhAd/Home-AssistantConfig#1]
Was looking through your presence build and I have to say I'm really impressed! However I can't seem to see what script this automation links to?

```
alias: 'MQTT person1 away'
trigger:
  - platform: homeassistant
    event: start
  - platform: numeric_state
    entity_id: sensor.person1_mobile_first_floor_rear
    below: 10
  - platform: numeric_state
    entity_id: sensor.person1_mobile_first_floor_front
    below: 10
action:
  **- service: script.mqtt_person1_status**
```

Any advice as I thought it would be person1_away but I may be looking at this too obvious

Thanks in advance

Dave
